version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: resume_db
    volumes:
      - "./db/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=resume_db
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pgdata:
